### ISSUE TITLE
I tried thead, tbody and tfoot but it still doesnt work

### ISSUE THREAD

**Issue by hoanganhduong** [hoanganhduong/quiz#3]
<img width="917" alt="Screen Shot 2020-04-10 at 11 58 26 PM" src="https://user-images.githubusercontent.com/55412298/79034875-3d737680-7b87-11ea-8dc5-88780d58eb24.png">
<img width="928" alt="Screen Shot 2020-04-10 at 11 58 33 PM" src="https://user-images.githubusercontent.com/55412298/79034877-3ea4a380-7b87-11ea-8fff-959dd3ca08bb.png">

@muxlowc

**Comment by muxlowc** [comment]
@hoanganhduong it looks like you have an extra space after your </tbody>, otherwise it looks right to me! Hopefully that works!
